# Generated by Django 4.1.3 on 2022-11-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_remove_clipsmodel_tag_clipsmodel_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clipsmodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='clipsmodel',
            name='tag',
            field=models.ManyToManyField(default='', related_name='tags', to='viewer.tagsmodel'),
        ),
    ]
