# Generated by Django 4.1.3 on 2022-11-22 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_category_course_clipsmodel_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clipsmodel',
            name='course',
        ),
        migrations.AddField(
            model_name='tagsmodel',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='viewer.category'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
