# Generated by Django 4.1.3 on 2022-11-22 00:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import viewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_remove_clipsmodel_course_tagsmodel_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsmodel',
            name='category',
        ),
        migrations.AlterField(
            model_name='clipsmodel',
            name='video',
            field=models.FileField(upload_to=viewer.models.create_course, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الالبوم')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='viewer.category', verbose_name='اسم الفئة')),
            ],
        ),
        migrations.AddField(
            model_name='clipsmodel',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='course', to='viewer.course'),
            preserve_default=False,
        ),
    ]
