# Generated by Django 4.1.3 on 2022-11-22 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_course_category_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsmodel',
            name='course',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='course_tag', to='viewer.course'),
            preserve_default=False,
        ),
    ]
