# Generated by Django 4.1.3 on 2022-11-22 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_tagsmodel_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clipsmodel',
            name='tag',
        ),
        migrations.DeleteModel(
            name='TagsModel',
        ),
    ]
